// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"


export default interface Hit {
  highlights: any[];
  index:      Index;
  type:       Index;
  result:     Result;
}

export enum Index {
  Song = "song",
}

export interface Result {
  annotation_count:                                number;
  api_path:                                        string;
  artist_names:                                    string;
  full_title:                                      string;
  header_image_thumbnail_url:                      string;
  header_image_url:                                string;
  id:                                              number;
  language:                                        Language;
  lyrics_owner_id:                                 number;
  lyrics_state:                                    LyricsState;
  path:                                            string;
  pyongs_count:                                    number;
  relationships_index_url:                         string;
  release_date_components:                         ReleaseDateComponents;
  release_date_for_display:                        string;
  release_date_with_abbreviated_month_for_display: string;
  song_art_image_thumbnail_url:                    string;
  song_art_image_url:                              string;
  stats:                                           Stats;
  title:                                           string;
  title_with_featured:                             string;
  url:                                             string;
  featured_artists:                                Artist[];
  primary_artist:                                  Artist;
}

export interface Artist {
  api_path:         string;
  header_image_url: string;
  id:               number;
  image_url:        string;
  is_meme_verified: boolean;
  is_verified:      boolean;
  name:             string;
  url:              string;
  iq?:              number;
}

export enum Language {
  En = "en",
  Fr = "fr",
}

export enum LyricsState {
  Complete = "complete",
}

export interface ReleaseDateComponents {
  year:  number;
  month: number;
  day:   number;
}

export interface Stats {
  unreviewed_annotations: number;
  concurrents?:           number;
  hot:                    boolean;
  pageviews:              number;
}
